name: Run tests
on: push
jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "18"
          check-latest: true
      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "19"
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: 2.10.0
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: lein deps
      - name: Print dependency tree
        run: |
          lein with-profile +dev deps :tree
          lein with-profile -dev,-user,-base deps :tree
      - name: Build JS runtime
        run: lein build-js
      - name: Run tests
        run: lein t
      - name: Run linter
        run: lein lint
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: logs
          path: target/*.log
